name: Product Healthchecks
run-name: ${{ github.actor }} is running Product Healthchecks ğŸ¥
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  Pre-Canary-Run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  Total-TypeScript-Canary:
    uses: './.github/workflows/playwright-total-typescript.yml'
  Pro-Tailwind-Canary:
    uses: './.github/workflows/playwright-protailwind.yml'
  Egghead-Canary:
    uses: './.github/workflows/playwright-egghead.yml'
